// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGiIYe5H8eFMUW01Tvv_GTpTxZDaU0-fc',
    appId: '1:886965243062:web:764e366135103f6889ea17',
    messagingSenderId: '886965243062',
    projectId: 'quiz-app-50bcb',
    authDomain: 'quiz-app-50bcb.firebaseapp.com',
    databaseURL: 'https://quiz-app-50bcb-default-rtdb.firebaseio.com',
    storageBucket: 'quiz-app-50bcb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-CkiqyMXpX9HrB0rM-_8gFZ06ve0iy-Y',
    appId: '1:886965243062:android:cc498c6ca6e3b9ce89ea17',
    messagingSenderId: '886965243062',
    projectId: 'quiz-app-50bcb',
    databaseURL: 'https://quiz-app-50bcb-default-rtdb.firebaseio.com',
    storageBucket: 'quiz-app-50bcb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM1qcsZ2QvjBYWaJRgHZucCQ0qCoaQ1eY',
    appId: '1:886965243062:ios:4f550f62bc97660989ea17',
    messagingSenderId: '886965243062',
    projectId: 'quiz-app-50bcb',
    databaseURL: 'https://quiz-app-50bcb-default-rtdb.firebaseio.com',
    storageBucket: 'quiz-app-50bcb.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM1qcsZ2QvjBYWaJRgHZucCQ0qCoaQ1eY',
    appId: '1:886965243062:ios:e37d0b84e4747f3f89ea17',
    messagingSenderId: '886965243062',
    projectId: 'quiz-app-50bcb',
    databaseURL: 'https://quiz-app-50bcb-default-rtdb.firebaseio.com',
    storageBucket: 'quiz-app-50bcb.appspot.com',
    iosBundleId: 'com.example.quizApp.RunnerTests',
  );
}
